#!/usr/bin/env bash

wid=$1
class=$2
instance=$3
consequences=$4

result() {
    eval "$consequences"
    [ "$state" ] || echo "$1"
}

	case "$class" in
		FloaTerm)
			result "state=floating center=on"
			;;
		Updating)
			result "state=floating sticky=on center=on"
			;;
		Pavucontrol)
			result "state=floating center=on"
			;;
		Virt-manager)
			result "state=floating desktop=^5 follow=on center=on"
			;;
		Thunar)
			result "state=pseudo_tiled desktop=^2 rectangle=966x576+0+0 follow=on"
			;;
		Spotify)
			result "state=pseudo_tiled desktop=^6 follow=on"
			;;
	esac

	case "$instance" in
		Toolkit)
			result "state=floating sticky=on rectangle=500x290+1054+593"
			;;
	esac
