#!/usr/bin/env bash
#   █████╗ ██████╗ ██████╗ ███████╗    ██╗      █████╗ ██╗   ██╗███╗   ██╗ ██████╗██╗  ██╗███████╗██████╗
#  ██╔══██╗██╔══██╗██╔══██╗██╔════╝    ██║     ██╔══██╗██║   ██║████╗  ██║██╔════╝██║  ██║██╔════╝██╔══██╗
#  ███████║██████╔╝██████╔╝███████╗    ██║     ███████║██║   ██║██╔██╗ ██║██║     ███████║█████╗  ██████╔╝
#  ██╔══██║██╔═══╝ ██╔═══╝ ╚════██║    ██║     ██╔══██║██║   ██║██║╚██╗██║██║     ██╔══██║██╔══╝  ██╔══██╗
#  ██║  ██║██║     ██║     ███████║    ███████╗██║  ██║╚██████╔╝██║ ╚████║╚██████╗██║  ██║███████╗██║  ██║
#  ╚═╝  ╚═╝╚═╝     ╚═╝     ╚══════╝    ╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
#	Script to control prefered apps to launch for all themes
# 	Author: z0mbi3
#	url: https://github.com/gh0stzk

WIDGET_DIR="$HOME/.config/bspwm/eww"

	case "$1" in
		--rice)
			RiceSelector
			;;
		--terminal)
			alacritty
			;;
		--floating)
			alacritty --class FloaTerm,FloaTerm -o window.dimensions.lines=22 window.dimensions.columns=90
			;;
	  --netmanager)
  	  NetManagerDM
  	  ;;
		--fetch)
			alacritty --hold --class FloaTerm,FloaTerm -o window.dimensions.lines=26 window.dimensions.columns=40 -e ~/.local/bin/sysfetch;;
		# Apps
		--filemanager)
			thunar
			;;
		--browser)
			floorp
			;;
		--editor)
			~/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate/bin/idea.sh
			;;
		# Eww Widgets
		--powermenu)
			eww -c "$WIDGET_DIR" open --toggle powermenu
			;;
		--usercard)
			eww -c "$WIDGET_DIR" open --toggle launchermenu
			;;
		--player)
			eww -c "$WIDGET_DIR" open --toggle music
			;;
		--calendar)
			eww -c "$WIDGET_DIR" open --toggle date
			;;
	  # My widgets
	  --games)
	    rofi -modi games -show games -theme games-default
	    ;;
	  --Rofi)
	    ~/.config/bspwm/scripts/rofi-network-manager.sh &
	    ;;
		*)
			echo "Invalid Option"
			;;
	esac
